version: '2.1'
services:
    postgres:
        container_name: pg_airflow
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        container_name: sc_airflow
        image: apache/airflow
        command: bash -c "pip install bs4 && webserver"
                

        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
    webserver:
        container_name: web_airflow
        image: apache/airflow
        entrypoint: ./scripts/entrypoint.sh
        command: bash -c "pip install bs4"
        restart: always
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"
